name: 'Push Tag'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      
      # Read the current version number from git ls-remote
      - id: current_version
        shell: bash
        run: |
          echo $(git tag | sort -V | tail -1)
          echo "version=$(git ls-remote --tag origin | cut -d '/' -f 3 | sort -V | tail -1)" >> $GITHUB_OUTPUT
      
      # Increment the patch version number by one
      - id: patch_version
        run: |
          major=$(echo "${{ steps.current_version.outputs.version }}" | awk -F'.' '{print $1}')
          minor=$(echo "${{ steps.current_version.outputs.version }}" | awk -F'.' '{print $2}')
          patch=$(echo "${{ steps.current_version.outputs.version }}" | awk -F'.' '{print $3}')
          new_patch=$((patch+1))
          new_version="$major.$minor.$new_patch"
          echo "Updating version to $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
      
      # Commit the changes to the repository without pushing
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.patch_version.outputs.new_version }}
          git push origin --tags