name: 'Test modules/cloud-init'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-cloud-init.yml'
      - 'modules/cloud-init/**'
      - 'tests/cloud-init/**'

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/labrats-work/ops-images/omnibus:latest

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Terraform Init
      run: terraform -chdir=tests/cloud-init init -backend-config=config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      name: Terraform Plan
      run: terraform -chdir=tests/cloud-init plan --var-file=default.tfvars -out=tfplan -input=false
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      name: Terraform Apply
      run: terraform -chdir=tests/cloud-init apply tfplan
    - 
      name: Terraform Destroy
      if: always()
      run: terraform -chdir=tests/cloud-init destroy --var-file=default.tfvars -auto-approve -input=false
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      name: Upload metadata file
      uses: actions/upload-artifact@v3
      with:
        path: tests/cloud-init/metadata
        if-no-files-found: error
    - 
      name: Test metadata file
      run: |
        cd tests/cloud-init
        diff metadata default/metadata || exit 1
        exit 0
    - 
      name: Upload network_config file
      uses: actions/upload-artifact@v3
      with:
        path: tests/cloud-init/network_config
        if-no-files-found: error
    - 
      name: Test network_config file
      run: |
        cd tests/cloud-init
        diff network_config default/network_config || exit 1
        exit 0
    - 
      name: Upload user_data file
      uses: actions/upload-artifact@v3
      with:
        path: tests/cloud-init/user_data
        if-no-files-found: error
    - 
      name: Test user_data
      run: |
        cd tests/cloud-init
        diff user_data default/user_data || exit 1
        exit 0