name: 'Test modules/hetzner/node'

on:
  workflow_dispatch:
  push:
    branches-ignore: 
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Create vars file for test.
      run: |
        cd tests/hetzner
        echo "hcloud_token = \"${{ secrets.HETZNER_TOKEN }}\"" >> default.tfvars
        echo "branch_name = \"${{ env.BRANCH_NAME }}\"" >> default.tfvars
    - 
      name: Update config files for test.
      run: |
        cd tests/hetzner
        sed -i 's|hetzner.name|${{ env.BRANCH_NAME }}|' files/node_config.json
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        chdir: tests/hetzner
        verb: plan
        init: yes
        varsFile: default.tfvars
        planFile: tfplan
    - 
      name: Terraform Apply
      uses: labrats-work/action-terraform@main
      with:
        chdir: tests/hetzner
        verb: apply
        init: yes
        varsFile: default.tfvars
        planFile: tfplan
    - 
      name: Sleep
      run: |
        echo "Will destroy node in 2 minutes"
        sleep 120
    - 
      if: always()
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        chdir: tests/hetzner
        verb: destroy
        init: yes
        varsFile: default.tfvars