name: 'Test modules/aws/node'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy-test.yml'
      - '.github/workflows/test-aws.yml'
      - 'modules/aws/**'
      - 'tests/aws/**'

permissions:
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/deploy-test.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix: 
        image: [ ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-* ]
        testpath: [ tests/aws/node ]
        
    with:
      IMAGE: ${{ matrix.image }}
      TESTPATH: ${{ matrix.testpath }}