name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches-ignore: 
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Checkout secrets repository.
      uses: actions/checkout@v3
      with:
        repository: tomp736/awesome_kubernetes_secrets
        token: ${{ secrets.SECRETS_PAT }}
        path: ./secrets
        ref: main
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: plan
        init: yes
        varsFile: secrets/${{ env.BRANCH_NAME }}.tfvars
        planFile: tfplan
    - 
      name: Terraform Apply
      uses: labrats-work/action-terraform@main
      with:
        chdir: tests/hetzner
        verb: plan
        init: yes
        planFile: tfplan