name: 'Test modules/hetzner'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-hetzner.yml'
      - 'modules/hetzner/**'
      - 'tests/hetzner/**'

permissions:
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/deploy-test.yml

    strategy:
      fail-fast: false
      matrix: 
        image: [ debian-11, fedora-37, rocky-9, ubuntu-22.04 ]
        testpath: [ tests/hetzner/node, tests/hetzner/node_group ]
        
    with:
      IMAGE: ${{ matrix.image }}
      TESTPATH: ${{ matrix.testpath }}