name: 'Deploy Test and Tag'

on:
  push:

permissions:
  contents: read

jobs:
  aws:
    uses: ./.github/workflows/deploy-test.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix: 
        image: [ ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-* ]
        testpath: [ tests/aws/node ]
        
    with:
      IMAGE: ${{ matrix.image }}
      TESTPATH: ${{ matrix.testpath }}

  hetzner:
    uses: ./.github/workflows/deploy-test.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix: 
        image: [ debian-11, fedora-37, rocky-9, ubuntu-22.04 ]
        testpath: [ tests/hetzner/node, tests/hetzner/node_group ]
        
    with:
      IMAGE: ${{ matrix.image }}
      TESTPATH: ${{ matrix.testpath }}

  push-tag:
    needs: [ aws, hetzner]
    uses: ./.github/workflows/push-tag.yml
    secrets: inherit