name: 'Test modules/cloud-init'

on:
  workflow_dispatch:
  push:
    branches-ignore: 
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        chdir: tests/cloud-init
        verb: plan
        init: yes
        planFile: tfplan
    - 
      name: Terraform Apply
      uses: labrats-work/action-terraform@main
      with:
        chdir: tests/cloud-init
        verb: apply
        init: yes
        planFile: tfplan
    - 
      name: Test metadata file
      run: |
        cd tests/cloud-init
        diff metadata default/metadata || exit 1
        exit 0
    - 
      name: Test networkconfig file
      run: |
        cd tests/cloud-init
        diff metadata default/metadata || exit 1
        exit 0
    - 
      name: Test userdatafile
      run: |
        cd tests/cloud-init
        diff metadata default/metadata || exit 1
        exit 0