name: 'Test - Aws'

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'modules/aws/**'
      - 'tests/aws/**'

jobs:
  aws:
    uses: ./.github/workflows/deploy-test.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix: 
        image: [ ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-* ]
        testpath: [ tests/aws/node ]
        
    with:
      IMAGE: ${{ matrix.image }}
      TESTPATH: ${{ matrix.testpath }}

  push-tag:
    needs: [ aws ]
    uses: ./.github/workflows/push-tag.yml
    secrets: inherit