name: 'Test modules/aws/node'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-aws.yml'
      - 'modules/aws/**'
      - 'tests/aws/**'

permissions:
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/deploy-test.yml

    strategy:
      fail-fast: false
      matrix: 
        image: [ debian-11, fedora-37, rocky-9, ubuntu-22.04 ]
        testpath: [ tests/aws/node ]
        
    with:
      IMAGE: ${{ matrix.image }}
      TESTPATH: ${{ matrix.testpath }}